{
 "title": "Vault / Core Metrics",
 "description": "Node States, Requests, Mounts, Seal",
 "time": { "from": "{{TEMPLATE_TIME_FROM}}", "to": "{{TEMPLATE_TIME_TO}}" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_core_active", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Is Unsealed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_core_unsealed", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Is Perf Standby",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_core_performance_standby", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Number of Mounts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (type, local) (vault_core_mount_table_num_entries)",
     "legendFormat": "type={{type}} local={{local}}"
    }
   ]
  },
  {
   "title": "Vault Authenticated Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vault_core_handle_request{quantile=\"0.95\"}",
     "legendFormat": "p95 {{instance}}"
    },
    {
     "expr": "vault_core_handle_request{quantile=\"0.99\"}",
     "legendFormat": "p99 {{instance}}"
    },
    {
     "expr": "rate(vault_core_handle_request_sum[$__rate_interval]) / rate(vault_core_handle_request_count[$__rate_interval])",
     "legendFormat": "avg {{instance}}"
    }
   ]
  },
  {
   "title": "Vault Login Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "vault_core_handle_login_request{quantile=\"0.95\"}",
     "legendFormat": "p95 {{instance}}"
    },
    {
     "expr": "vault_core_handle_login_request{quantile=\"0.99\"}",
     "legendFormat": "p99 {{instance}}"
    },
    {
     "expr": "rate(vault_core_handle_login_request_sum[$__rate_interval]) / rate(vault_core_handle_login_request_count[$__rate_interval])",
     "legendFormat": "avg {{instance}}"
    }
   ]
  },
  {
   "title": "Vault Req per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(vault_core_handle_request_count[$__rate_interval])",
     "legendFormat": "handle_request_count"
    },
    {
     "expr": "rate(vault_core_handle_login_request_count[$__rate_interval])",
     "legendFormat": "handle_login_request_count"
    }
   ]
  },
  {
   "title": "Audit Log Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "vault_audit_log_request" },
    { "expr": "vault_audit_log_response" }
   ]
  },
  {
   "title": "Seal Encrypt/Decrypt Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "vault_seal_encrypt_time" },
    { "expr": "vault_seal_decrypt_time" }
   ]
  },
  {
   "title": "Seal Encrypt/Decrypt Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(vault_seal_encrypt[$__rate_interval])"
    },
    {
     "expr": "rate(vault_seal_decrypt[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Entity Count",
   "type": "timeseries",
   "description": "Only reported every 10 minutes ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "vault_identity_entity_count" }
   ]
  },
  { "title": "Operational Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Vault Targets Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"vault\"})"
    }
   ]
  },
  {
   "title": "Unsealed Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vault_core_unsealed)" }
   ]
  },
  {
   "title": "Leader Changes (5m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "changes(vault_core_active[5m])" }
   ]
  }
 ]
}